# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
# This is to create 4 vms. If you want to change vms to up, change interation
# loop. Need improvement
VM=1
  (1..VM).each do |i|
    config.vm.define "node#{i}", primary: (i == 1 ? "true" : "false") do |node|
# Box image to pull
      node.vm.box = "fike/docker"
      node.vm.hostname = "node#{i}"
# For vms to communicate each other
      node.vm.network "private_network", ip: "192.168.40.1#{i}"
      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end
  end
end
